name: Build CRX Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Extension
        run: yarn build
        env:
          EDHS_VERSION: ${{ github.ref_name }}
          EDHS_MODE: ${{ contains(github.ref_name, 'pre') && 'PRERELEASE' || 'PRODUCTION' }}

      - name: Zip Artifact
        run: zip -r EDHS_${{ github.ref_name }}.zip ./dist"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file: EDHS_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
