name: Build CRX Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    environment: ${{ contains(github.ref_name, 'pre') && 'PRERELEASE' || 'PRODUCTION' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const version = tag.replace('v', '')
            core.setOutput('version', version)

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Extension
        run: yarn build
        env:
          EDHS_VERSION: ${{ steps.set_version.outputs.version }}
          EDHS_MODE: ${{ secret.EDHS_MODE }}

      - name: Zip Artifact
        run: zip -r EDHS_${{ github.ref_name }}.zip "./dist"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ contains(github.ref_name, 'pre') }}
          files: EDHS_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Chrome Web Store
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: ${{ secrets.EDHS_EXT_ID }}
          zip: EDHS_${{ github.ref_name }}.zip
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
